"""meta_rl/git_agent_exporter.py — ATOM-META-RL-013: GitAgent Export for Strategies"""

from __future__ import annotations

import hashlib
import json
import logging
import random
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)
GIT_EXPORT_ENABLED = True
EXPORT_ON_EVOLUTION = False


@dataclass
class ExportResult:
    slug: str
    path: str
    validated: bool
    errors: list[str]


def _slug_safe(text: str) -> str:
    keep = frozenset("abcdefghijklmnopqrstuvwxyz0123456789-")
    slug = "".join(c if c in keep else "-" for c in text.lower().strip())
    slug = re.sub(r"--+", "-", slug).strip("-")
    return slug[:40] or "strategy"


def _slug_for_strategy(strategy: Any) -> str:
    chrom = getattr(strategy, "chromosome", {})
    conf = chrom.get("confidence_threshold", 60.0)
    pos = chrom.get("position_size_pct", 15.0)
    atr = chrom.get("atr_multiplier", 2.0)
    seed_str = f"{conf:.0f}_{pos:.0f}_{atr:.1f}_{random.random():.4f}"
    short_hash = hashlib.md5(seed_str.encode()).hexdigest()[:8]
    return short_hash


def _regime_label(rf: str) -> str:
    mapping = {
        "ALL": "ALL",
        "BULL_ONLY": "BULL-RESTRICTED",
        "BEAR_ONLY": "BEAR-RESTRICTED",
    }
    return mapping.get(rf, rf)


def export_strategy(strategy: Any, version_tag: str = None, output_dir: str = None) -> ExportResult:
    if not GIT_EXPORT_ENABLED:
        return ExportResult(slug="", path="", validated=False, errors=["GIT_EXPORT_ENABLED=False"])
    try:
        output_dir = output_dir or "integrations/gitagent/exported_strategies"
        short = _slug_for_strategy(strategy)
        slug = f"meta-rl-{short}"
        if version_tag:
            slug = f"{slug}-{version_tag}"
        pkg = Path(output_dir) / slug
        pkg.mkdir(parents=True, exist_ok=True)
        sub = pkg / "sub_agents" / slug
        sub.mkdir(parents=True)
        chrom = getattr(strategy, "chromosome", {})
        gen = getattr(strategy, "generation", 0)
        ev = getattr(strategy, "evaluation", None)
        eval_dict = getattr(ev, "to_dict", lambda: {})()
        risk_pnl = eval_dict.get("risk_adjusted_pnl", 0.0)
        sharpe_val = eval_dict.get("sharpe", 0.0)
        regime = chrom.get("regime_filter", "ALL")
        conf_base = int(chrom.get("confidence_threshold", 60))
        model_conf = {"confidence_base": conf_base}
        agent_yaml = {
            "name": slug,
            "description": f"Meta-RL strategy gen={gen} conf={conf_base}",
            "version": f"1.{gen}.0",
            "model": model_conf,
            "capabilities": ["meta-rl-strategy", f"regime={regime}"],
            "tools": [],
            "sub_agents": [slug],
            "compliance": {"risk_level": _regime_label(regime)},
            "workflows": ["evaluate"],
        }
        _write_yaml(agent_yaml, pkg / "agent.yaml")
        soul = f"""# SOUL.md — {slug}
Generated by AstroFin ATOM-META-RL-013.
## Identity
Meta-RL strategy generation {gen}.
## Principles
1. Evaluate each bar via strategy.evaluate().
2. Report signal with confidence.
3. Apply AMRE validation.
## Guidelines
- regime={regime}, confidence_base={conf_base}
- Risk: sharpe={sharpe_val:.3f} risk_pnl={risk_pnl:+.4f}.
"""
        _write_text(soul, pkg / "SOUL.md")
        rules = f"""# RULES.md
## Market Rules
1. Evaluate bar: signal_strength + momentum + mean_reversion.
2. Confidence < {conf_base} → NEUTRAL.
3. regime={regime} filter active.
4. Stop-loss/take-profit via atr_multiplier={chrom.get("atr_multiplier", 2.0):.1f}.
"""
        _write_text(rules, pkg / "RULES.md")
        duties = f"""# DUTIES.md
## Output Schema
signal: LONG | SHORT | NEUTRAL, confidence: int, reasoning: str.
risk_adjusted_pnl: {risk_pnl:+.4f} sharpe={sharpe_val:.3f}.
"""
        _write_text(duties, pkg / "DUTIES.md")
        skill = f"""# {slug}
Meta-RL generated strategy.
## Instructions
Use strategy.chromosome={chrom}.
## Output
{{"signal": str, "confidence": int}}.
"""
        _write_text(skill, sub / "SKILL.md")
        _write_text(f"name: {slug}\ntype: strategy_agent", sub / "manifest.yaml")
        _write_json(dict(chrom), pkg / "strategy_params.json")
        readme = f"""# {slug}
Meta-RL strategy gen={gen} exported as GitAgent package.
Generated: {datetime.utcnow().isoformat()}
## Parameters
```json
{json.dumps(chrom, indent=2)}
```
## Metrics
risk_adjusted_pnl={risk_pnl:+.4f} sharpe={sharpe_val:.3f}
## Usage
```python
from meta_rl.git_agent_exporter import load_strategy
strategy = load_strategy("{pkg}")
```
"""
        _write_text(readme, pkg / "README.md")
        logger.info(f"[META-RL-GIT] Exported {slug} -> {pkg}")
        return ExportResult(slug=slug, path=str(pkg), validated=True, errors=[])
    except Exception as ex:
        logger.warning(f"[META-RL-GIT] export failed: {ex}")
        return ExportResult(slug="", path="", validated=False, errors=[str(ex)])


def _write_text(content: str, path: Path):
    try:
        Path(path).write_text(content, encoding="utf-8")
    except Exception as ex:
        logger.warning(f"[META-RL-GIT] write_text failed {path}: {ex}")


def _write_yaml(data: dict, path: Path):
    try:
        with open(path, "w") as f:
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)
    except Exception as ex:
        logger.warning(f"[META-RL-GIT] yaml dump failed {path}: {ex}")


def _write_json(data: dict, path: Path):
    try:
        with open(path, "w") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as ex:
        logger.warning(f"[META-RL-GIT] json dump failed {path}: {ex}")


def load_strategy(package_path: str) -> Any | None:
    try:
        from strategies.generator import GeneratedStrategy

        pkg = Path(package_path)
        params_path = pkg / "strategy_params.json"
        if not params_path.exists():
            logger.warning(f"[META-RL-GIT] No params: {params_path}")
            return None
        params = json.loads(params_path.read_text())
        chrom = {str(k): v for k, v in params.items()}
        strategy = GeneratedStrategy(chromosome=chrom, generation=1)
        logger.info(f"[META-RL-GIT] Loaded {package_path}")
        return strategy
    except Exception as ex:
        logger.warning(f"[META-RL-GIT] load failed {package_path}: {ex}")
        return None
