global:
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"

route:
  receiver: 'telegram'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        bot_token: ${TELEGRAM_BOT_TOKEN}
        chat_id: ${TELEGRAM_CHAT_ID}
        parse_mode: 'HTML'
        message: |
          <b>{{ .Status | toUpper }}</b>: {{ .CommonAnnotations.summary }}
          <i>{{ .CommonAnnotations.description }}</i>
          <b>Severity:</b> {{ .CommonLabels.severity }}
